version: "1.0"
info:
  model: int-scaffold
packages:
- name: GitIssueTest1Project
  gitServerName: GH_SH
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.gitissuetest1.integrations:Test1
  packages:
  - name: GitIssueTest1Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.7
